defaults:
  namespace: coder
  sessions: false
  client: memcache-client
  with_finders: true
development:
  servers:
    - 127.0.0.1:11211
production:
  servers:
    - 127.0.0.1:11211
    - 127.0.0.1:11211
